import './global.css';
import { ThemeProvider } from '../components/material';
import { Toaster } from '../components/shadcn/toast/toaster';

export const metadata = {
  title: 'Welcome to art-effix-shell',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div>

          </div>
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
